### ISSUE TITLE
Install Failes

### ISSUE THREAD

**Issue by jc1396** [wavestone-cdt/abaddon#1]
Getting the error listed below when trying to install:

PPLYING DJANGO MIGRATIONS AND CREATING A NEW USER

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/model_checks.py", line 15, in check_all_models
    models = apps.get_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 178, in get_models
    self.check_models_ready()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/database.py", line 9, in check_database_backends
    for conn in connections.all():
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 216, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 204, in fetch_command
    app_name = commands[subcommand]
KeyError: 'createsuperuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 211, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'

**Comment by Ibrahimous** [comment]
Hi,
Which command did you launch to get the above error?
Looks like you tried to launch manual commands with manage.py: have you configured aws and launched install.sh?

**Comment by jc1396** [comment]
Yes, I configured AWS and launched the install.sh script.  I even deleted
everything and tried a second time with the same result.

I am running this on the latest version of Kali on vmware.

Thanks  Jerry.

**Comment by Ibrahimous** [comment]
So you installed everything and it worked, then laucnhed:
bash abaddon.sh
?
And just to be sure: from which directory are you launching abaddon.sh?
The line: "No module named 'abaddon.settings'" makes me think

**Comment by jc1396** [comment]
When I run the install.sh script from the /opt/abaddon/setup folder, it
fails with error message:

APPLYING DJANGO MIGRATIONS AND CREATING A NEW USER


Traceback (most recent call last):
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 361, in execute
    self.check()
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 390, in check
    include_deployment_checks=include_deployment_checks,
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/checks/registry.py",
line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/checks/model_checks.py",
line 15, in check_all_models
    models = apps.get_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py",
line 178, in get_models
    self.check_models_ready()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py",
line 140, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 381, in execute_from_command_line
    utility.execute()
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py",
line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'
Traceback (most recent call last):
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 361, in execute
    self.check()
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 390, in check
    include_deployment_checks=include_deployment_checks,
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py",
line 64, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File
"/usr/local/lib/python3.7/dist-packages/django/core/checks/registry.py",
line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/checks/database.py",
line 9, in check_database_backends
    for conn in connections.all():
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
216, in all
    return [self[alias] for alias in self]
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py",
line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 381, in execute_from_command_line
    utility.execute()
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/base.py",
line 336, in run_from_argv
    connections.close_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
219, in close_all
    for alias in self:
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
213, in __iter__
    return iter(self.databases)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py",
line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line
147, in databases
    self._databases = settings.DATABASES
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'
Traceback (most recent call last):
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 204, in fetch_command
    app_name = commands[subcommand]
KeyError: 'createsuperuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 381, in execute_from_command_line
    utility.execute()
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File
"/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py",
line 211, in fetch_command
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/dist-packages/django/conf/__init__.py",
line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'abaddon.settings'

**Comment by Tirititelu** [comment]
Same problem here.

**Comment by t94j0** [comment]
There's a file called settings.py.example that needs to be moved to settings.py. The problem with settings.py is that there are modules like `findings` and `engines` that don't exist (maybe did at one point or maybe on a maintainer's computer). Even if you fix those, the code supposes that a module called `events` exists so execution still fails.

This makes me believe that all the code hasn't been released yet.

**Comment by Ibrahimous** [comment]
Thanks for your comments, you are right: the settings.py.example was not the settings.py anonymised but an erroneous (old) settings file. It is fixed, and the README now mentions that settings.py.example should be renamed (commit a24545f).
I just cloned the repo on a fresh machine and this seems sufficient to work, I'll close the issue then.
If anything goes wrong again, don't hesitate to reopen the issue or create another one.
