### ISSUE TITLE
Issue druning instalation

### ISSUE THREAD

**Issue by Chandr01** [wavestone-cdt/abaddon#9]
path('delivery/', include('delivery.urls')), # => MOVE aws in delivery 
  File "/usr/local/lib/python3.8/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/abaddon/delivery/urls.py", line 10, in <module>
    path('', include('aws.urls')),
  File "/usr/local/lib/python3.8/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/abaddon/aws/urls.py", line 3, in <module>
    from . import views
  File "/opt/abaddon/aws/views.py", line 20, in <module>
    c=f.readlines()[1].split('=')
IndexError: list index out of range

**Comment by Chandr01** [comment]
APPLYING DJANGO MIGRATIONS AND CREATING A NEW USER

**Comment by Ibrahimous** [comment]
Hi,
I don't understand your issue, when did it occur? 

Looking at your error, you might have an not filled pre-requisite: did you launch aws configure beforehand?
If yes, can you provide the output of:
`ls ~/.aws/`
?
Regards

**Comment by Chandr01** [comment]
Hello!
I apologize for describing the problem so inconsistently.
Now I will describe everything in steps
OS Digital Ocean > Debian 10.3 x64 > 1 vCPUs / 1GB / 25GB Disk

1) git clone git@github.com:wavestone-cdt/abaddon.git

fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
root@abaddon:~#

workaround: git clone https://github.com/wavestone-cdt/abaddon.git

cd abaddon

2)aws configure
-bash: aws: command not found

workaround:
root@abaddon:~# pip3 --version
-bash: pip3: command not found
root@abaddon:~#
root@abaddon:~#
root@abaddon:~# apt install curl
root@abaddon:~# apt install python-pip
root@abaddon:~# apt install python3-pip

root@abaddon:~# pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

root@abaddon:~# pip --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 20.1 from /root/.local/lib/python2.7/site-packages/pip (python 2.7)

root@abaddon:~# pip3 install awscli --upgrade --user
root@abaddon:~# export PATH=~/.local/bin:$PATH
root@abaddon:~# aws --version
aws-cli/1.18.60 Python/3.7.3 Linux/4.19.0-8-cloud-amd64 botocore/1.16.10

root@abaddon:~# aws configure
AWS Access Key ID [None]: My Access key
AWS Secret Access Key [None]: My Secret Key
Default region name [None]: us-east-2c
Default output format [None]:

root@abaddon:~# ls ~/.aws/
config  credentials
root@abaddon:~# cat ~/.aws/credentials
[default]
aws_access_key_id = XXXXXXXXX
aws_secret_access_key = XXXXXXXX/XXXXXXXXX
root@abaddon:~# cat ~/.aws/config
[default]
region = us-east-2c
root@abaddon:~#

3) 
root@abaddon:~/abaddon# mv abaddon/settings.py.sample abaddon/settings.py
root@abaddon:~/abaddon# sed -i 's/yourPasswordHere/<databasepassword>/g' abaddon/settings.py

4) 
root@abaddon:~/abaddon# bash setup/install.sh
a lot of instalation

Resolving deltas: 100% (59/59), done.


PATCHING SIX


sed: can't read /root/.local/lib/python3.7/site-packages/datetimewidget/widgets.py: No such file or directory
root@abaddon:~/abaddon#


===================================================Trying to manualy create file======================================================================

root@abaddon:~/abaddon# mkdir -p /root/.local/lib/python3.7/site-packages/datetimewidget/

root@abaddon:~/abaddon# touch /root/.local/lib/python3.7/site-packages/datetimewidget/widgets.py
root@abaddon:~/abaddon#

root@abaddon:~/abaddon# bash setup/install.sh
a lot of instalation, but this time less

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/abaddon/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/loader.py", line 283, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "red-teamer"
FATAL:  password authentication failed for user "red-teamer"

root@abaddon:~/abaddon#

**Comment by Chandr01** [comment]
Full logs - https://github.com/Chandr01/logs/blob/master/digital_ocean/abaddon.log

**Comment by Ibrahimous** [comment]
Hi,
2 problems upthere:
- doing everything as root is a very bad (functional & security) practice. You get an example of that during the installation. pip-ing things as root often creates such problems
- At the end you get simply an authentication failure to the database. Check that the password you've got in settings.py is the same as the one you used during postegresql installation

Thx for the typo in README for the git clone thing, I've just fixed it.
